BINARY   := qnap-docker-mdnsd
CMD_DIR  := ./cmd/qnap-docker-mdnsd
DIST_DIR := ./dist
SHARED   := ./shared

# Default cross-compilation target: x86_64 QNAP
# For ARM QNAP (e.g., TS-xxx), override: make cross-build GOARCH=arm64
# For 32-bit ARM QNAP, override: make cross-build GOARCH=arm
GOOS     ?= linux
GOARCH   ?= amd64

QBUILD   := qbuild

.PHONY: all build cross-build test lint clean run dist install-qdk qbuild qpkg qinstall help

all: build

help:
	@echo "Targets:"
	@echo "  build        - Build for host platform"
	@echo "  cross-build  - Cross-compile for QNAP (GOOS=linux GOARCH=amd64)"
	@echo "  test         - Run all unit tests"
	@echo "  lint         - Run go vet"
	@echo "  clean        - Remove build artifacts"
	@echo "  dist         - Cross-compile and stage binary"
	@echo "  run          - Run daemon locally (requires Docker)"
	@echo ""
	@echo "QPKG targets (requires QDK):"
	@echo "  install-qdk  - Download and install QDK qbuild tool"
	@echo "  qbuild       - Run qbuild to produce .qpkg archive"
	@echo "  qpkg         - cross-build + qbuild (one-step build)"
	@echo "  qinstall     - Create unpacked qinstall.sh for fast iteration"
	@echo ""
	@echo "Cross-compilation:"
	@echo "  make cross-build              -> linux/amd64 (x86_64 QNAP)"
	@echo "  make cross-build GOARCH=arm64 -> linux/arm64 (ARM QNAP)"
	@echo "  make cross-build GOARCH=arm   -> linux/arm   (32-bit ARM QNAP)"
	@echo ""
	@echo "For Apple Silicon Macs building for x86_64 QNAP:"
	@echo "  make cross-build GOOS=linux GOARCH=amd64 CGO_ENABLED=0"

build:
	go build -o $(BINARY) $(CMD_DIR)

cross-build:
	GOOS=$(GOOS) GOARCH=$(GOARCH) CGO_ENABLED=0 go build \
		-o $(DIST_DIR)/$(BINARY)-$(GOARCH) $(CMD_DIR)

dist: cross-build
	@echo "Binary: $(DIST_DIR)/$(BINARY)-$(GOARCH)"
	@echo "Run 'make qbuild' to build the QPKG, or copy manually:"
	@echo "  cp $(DIST_DIR)/$(BINARY)-$(GOARCH) $(SHARED)/$(BINARY)"

test:
	go test -v ./...

lint:
	go vet ./...

clean:
	rm -f $(BINARY)
	rm -rf $(DIST_DIR)/
	rm -f $(SHARED)/$(BINARY)

# Convenience: run locally (requires Docker)
run: build
	./$(BINARY)

# ------------------------------------------------------------------
# QPKG / QDK targets
# ------------------------------------------------------------------

# QDK acquisition path:
#
# QNAP provides the QDK (QNAP Development Kit) which includes qbuild.
# The recommended approach depends on your platform:
#
#   macOS / Linux (x86_64):
#     1. Download QDK from https://www.qnap.com/en/utilities/essentials
#        (search for "QDK" or "QNAP Development Kit")
#     2. A QNAP ID (QID) account may be required for download access.
#     3. Install the .qpkg on a QNAP NAS, then copy /usr/local/sbin/qbuild
#        and supporting files from the NAS to a Linux build machine, or
#        build directly on the NAS via SSH.
#
#   Docker alternative (any platform):
#     The QNAP development community maintains unofficial Docker images
#     with qbuild pre-installed for CI pipelines.
#
#   QNAP NAS (native):
#     Install QDK via App Center, then run qbuild over SSH.
#
# Once qbuild is in PATH, run: make qbuild

QDK_URL ?= https://www.qnap.com/en/utilities/essentials

install-qdk:
	@echo "=== QDK / qbuild Setup ==="
	@echo ""
	@echo "qbuild was not found in PATH."
	@echo ""
	@echo "Option 1: Install on a QNAP NAS (easiest)"
	@echo "  1. Visit $(QDK_URL)"
	@echo "  2. Download QDK (QNAP Development Kit) .qpkg"
	@echo "  3. Install via App Center on your QNAP NAS"
	@echo "  4. Run: ssh admin@<nas> \"cd /path/to/qpkg && qbuild\""
	@echo ""
	@echo "Option 2: Copy qbuild from NAS to a Linux build machine"
	@echo "  scp admin@<nas>:/usr/local/sbin/qbuild /usr/local/bin/"
	@echo "  # Also copy supporting libraries from /usr/local/lib/qdk/"
	@echo ""
	@echo "Option 3: Use an unofficial Docker image with qbuild pre-installed"
	@echo "  (Search Docker Hub for 'qnap qbuild' images)"
	@echo ""
	@echo "Once qbuild is available, run: make qbuild"

# Run qbuild to produce the .qpkg archive.
# The --force-config flag registers config.local.yaml as a QPKG_CONFIG
# so upgrades preserve operator-managed runtime config.
qbuild: check-qbuild
	$(QBUILD) --force-config

# One-step: cross-compile then build the QPKG.
qpkg: cross-build check-qbuild
	cp $(DIST_DIR)/$(BINARY)-$(GOARCH) $(SHARED)/$(BINARY)
	$(QBUILD) --force-config

# Generate a qinstall.sh script for fast iteration on package-install logic
# without rebuilding the .qpkg archive every time.
qinstall: cross-build
	cp $(DIST_DIR)/$(BINARY)-$(GOARCH) $(SHARED)/$(BINARY)
	@echo "#!/bin/sh" > qinstall.sh
	@echo "# Unpacked QPKG installer for fast iteration." >> qinstall.sh
	@echo "# Generated by 'make qinstall'. Edit shared/ files and re-run this script." >> qinstall.sh
	@echo "" >> qinstall.sh
	@echo "QPKG_NAME=qnap-docker-mdns" >> qinstall.sh
	@echo "INSTALL_ROOT=/tmp/qnap-docker-mdns-qpkg" >> qinstall.sh
	@echo "" >> qinstall.sh
	@echo "# Copy the shared/ payload to a temporary root that mirrors" >> qinstall.sh
	@echo "# the QNAP-managed QPKG install path." >> qinstall.sh
	@echo "rm -rf \$${INSTALL_ROOT}" >> qinstall.sh
	@echo "mkdir -p \$${INSTALL_ROOT}" >> qinstall.sh
	@echo "cp -r shared/* \$${INSTALL_ROOT}/" >> qinstall.sh
	@echo "cp qpkg.cfg \$${INSTALL_ROOT}/" >> qinstall.sh
	@echo "" >> qinstall.sh
	@echo "echo \"Payload staged at \$${INSTALL_ROOT}\"" >> qinstall.sh
	@echo "echo \"Copy to the NAS or test environment:\"" >> qinstall.sh
	@echo "echo \"  scp -r \$${INSTALL_ROOT}/* admin@<nas>:<qpkgs-dir>/qnap-docker-mdns/\"" >> qinstall.sh
	@chmod +x qinstall.sh
	@echo "Created: qinstall.sh"
	@echo "Edit shared/ files, then run: sh qinstall.sh"

check-qbuild:
	@command -v $(QBUILD) >/dev/null 2>&1 || { \
		echo "Error: qbuild not found in PATH."; \
		echo "Run 'make install-qdk' for setup instructions."; \
		exit 1; \
	}
